# spring
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/study/spring-boot-jpa/db/jpashop;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# logging
logging:
  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
